name: Metrics
on:
  schedule: 
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          config_display: large
          config_timezone: Asia/Taipei
          base: header
          plugin_languages: yes
          token: ${{ secrets.METRICS_TOKEN }}
