name: Insights
on:
  schedule: 
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push:
    branches: master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: data
      
      - name: generate github metric
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          repositories_affiliations: owner, collaborator
          config_display: large
          commits_authoring: ${{ secrets.USER_NAME }}
          config_padding: 8 + 12%
          optimize: svg
          experimental_features: --optimize-svg
          config_timezone: Asia/Taipei
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_details: percentage, lines
          plugin_lines: yes
          plugin_traffic: yes
          output_action: none
        
      - name: generate snake of github contribution
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg?palette=github-dark
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: push svg to the output branch
        run: |
          git add /metrics_renders/github-metrics.svg
          git commit -m "update github-metrics.svg"
          git add /data/github-snake.svg
          git commit -m "update github-snake.svg"
          git push
