name: Metrics
on:
  schedule: 
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_display: columns
          optimize: svg
          experimental_features: --optimize-svg
          config_timezone: Asia/Taipei
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          
