name: Metrics
on:
  schedule: 
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
