name: Metrics
on:
  schedule: 
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_display: large
          optimize: svg
          experimental_features: --optimize-svg
          config_timezone: Asia/Taipei
          base: header, activity, repositories, metadata
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_traffic: yes
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
