name: Metrics
on:
  schedule: 
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_display: large
          commits_authoring: garyellow, guanying1110, gary20011110@gmail.com
          config_padding: 8 + 12%
          optimize: svg
          experimental_features: --optimize-svg
          config_timezone: Asia/Taipei
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_details: percentage, lines
          plugin_lines: yes
          plugin_traffic: yes
